version: "3"
services:
    postgres:
        image: "postgres:9.6"
        restart: always
        container_name: "postgres"
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"

    pgadmin:
        restart: always
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin
            - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - 5051:80

    # uncomment initdb if you need initdb at first run
    # initdb:
    #     build: .
    #     entrypoint: airflow initdb
    #     depends_on:
    #         - postgres

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        ports:
            - "8080:8080"
        entrypoint: airflow webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    
    scheduler:
        build: .
        restart: always
        depends_on:
            - postgres
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        entrypoint: airflow scheduler
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    
    redis:
        image: redis:5.0.5
        ports:
            - "6379:6379"   
        restart: always
        
    flower:
        build: .
        restart: always
        depends_on:
            - postgres
            - redis
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        entrypoint: airflow flower
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-flower.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        ports:
            - "5555:5555"
            